# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouseAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouseID', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderItemID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thresholdLevel',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorEmail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendorID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
