# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itake', '0002_auto_20170415_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itake.Warehouse'),
        ),
    ]
