# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itake', '0003_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=20),
        ),
    ]
